"""Messaging System Configuration"""

# Anti-Death-Loop Limits
MAX_ROUNDS = 10
MAX_MESSAGES_PER_THREAD = 20
MAX_DEPTH = 5

# Timeouts
MESSAGE_TIMEOUT = 30
THREAD_TIMEOUT = 240
COOLDOWN_BETWEEN_MESSAGES = 5

# Rate Limiting
MAX_CONCURRENT_THREADS = 3
MAX_MESSAGES_PER_AGENT = 10
AGENT_COOLDOWN = 60

# Cost Tracking
MAX_API_CALLS_PER_THREAD = 50
MAX_COST_PER_THREAD = 1.00

# Kill Switches
KILL_SWITCH_ENABLED = True
AUTO_KILL_ON_ERROR = 3

# Paths
MESSAGING_DIR = "/opt/data/shared/messaging"
THREADS_DIR = f"{MESSAGING_DIR}/threads"
ARCHIVE_DIR = f"{MESSAGING_DIR}/archive"
KILL_SWITCH_FILE = f"{MESSAGING_DIR}/KILL_SWITCH"
